name: market
description: A Waves Market unofficial app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  flutter_redux: ^0.8.2
  flutter_phoenix: ^1.0.0

  # UI
  cupertino_icons: ^1.0.2

  # Navigation
  routemaster: ^1.0.0

  # Dart data class
  json_serializable: ^5.0.2

  # Code generators
  json_annotation: ^4.1.0
  build_runner: ^2.1.2

  # Network
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true